### ISSUE TITLE
Alternative notification services

### ISSUE THREAD

**Issue by NDuggan** [rhardih/pong#1]
As mentioned on Reddit, it would be nice to be able to integrate this with other services or APIs instead of (or as well as) email.

For example I would personally like to use it with a [Telegram bot](https://core.telegram.org/bots/api#sendmessage) (as it's free, compared to a premium iOS push notification service such as IFTTT/Zapier + Pushover).

Typically you would create a Telegram bot by interacting with "BotFather" in the Telegram app. This will get you a `BOT_API_KEY` so that you can send message as the bot. You will also need a `CHAT_ID` so that you can send messages to yourself from the bot.

Example API call:
```
https://api.telegram.org/bot<BOT_API_KEY>/sendMessage?chat_id=<CHAT_ID>&text=<MESSAGE_CONTENT"
```

**Comment by rhardih** [comment]
I've put up preliminary pull request, with an initial working implementation here: https://github.com/rhardih/pong/pull/2

Initially you have to run a rake task, which runs the bot you create, and then prompt it in chat, in order to get that chats id. I don't know if there's an easier way to get the chat id, but it works for now and it's only a one time thing, as I believe chat ids are permanent.

I'm thinking it might be worthwhile putting this into some form of editable application settings at some point, and also provide a setting of either/or, with regards to emails being sent simultaneously.
